spring.application.name=biblioteca-api

spring.data.mongodb.uri=mongodb+srv://adminBiblioteca:BLHlTB54ZJEds6eB@cluster0.vitorwg.mongodb.net/biblioteca_db?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=biblioteca_db

server.port=8080
